image: docker
services:
  - docker:dind

variables:
  DB_PASSWORD: $DB_PASSWORD
  VERCEL_TOKEN: $VERCEL_TOKEN
  VERCEL_LINK: $VERCEL_LINK

build-job:
  stage: build
  script:
    - mkdir db
    - echo $DB_PASSWORD > db/password.txt
    - echo $VERCEL_TOKEN > vercel.txt
    - mkdir app/.vercel
    - echo $VERCEL_LINK > app/.vercel/project.json
    - apk add --no-cache docker-compose
    -  ./dev-up.bash

test-api:
  stage: test
  script:
    - echo "This job tests something"
    - docker exec scratch-app /bin/bash -c "cd ../backend && ../run_tests.bash"

test-app:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

test-e2e:
  stage: test
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
