image: node:16-alpine

variables:
  DB_PASSWORD: $DB_PASSWORD
  VERCEL_TOKEN: $VERCEL_TOKEN
  VERCEL_LINK: $VERCEL_LINK

stages:
  - build
  - test
  - deploy

install-dependencies:
  stage: build
  cache:
    key:
      files:
        - app/package-lock.json
    paths:
      - app/node_modules
    policy: pull-push
  # only:
  #   refs:
  #     - merge_requests
  #     - main
  #   changes:
  #     - package-lock.json
  script:
    - cd app
    - echo "Installing Node Dependencies"
    - npm ci
    - echo "Installing Angular CLI"
    - npm install @angular/cli@14

test-api:
  image: golang
  stage: test
  script:
    - cd ./backend
    - echo "Running Go Tests"
    - /bin/bash ../run_tests.bash

test-app:
  stage: test
  image: node:16-alpine
  before_script:
    - apk add chromium
    - export CHROME_BIN=/usr/bin/chromium-browser
  cache:
    key:
      files:
        - app/package-lock.json
    paths:
      - app/node_modules
    policy: pull
  script:
    - cd app
    - echo "Lint Angular app"
    - npm run lint
    - echo "Run Angular app test cases"
    - npm run test:prod

test-e2e:
  stage: test
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
