version: "3.7"

services:
  app:
    build:
      context: app
      target: builder
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules

  backend:
    build:
      context: api
      target: builder
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=scratchcode
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
