version: "3.7"

services:
# convert this to handle both frontend angular and api
  app:
    container_name: scratch-app
    build:
      context: ./app
      target: dev
      args:
        USERNAME: "user"
        GROUPNAME: "user"
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    ports:
      - 3000:3000 # port golang API uses
    secrets:
      - db-password
      - vercel-token
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # angular dirs
      - ./app:/node/app
      - /node/app/node_modules
      # api dirs
      - ./.vercel:/node/.vercel
      - ./backend:/node/backend
      - ./go.work:/node/go.work
      - ./run_tests.bash:/node/run_tests.bash

# test db connection
  db:
    image: mysql:8
    container_name: scratch-db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=scratchcode
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
  vercel-token:
    file: vercel.txt
