name: Angular App CI
run-name: Running Angular Tests 🚀
on:
  push:
    branches: ["main", "dev/*"]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    defaults:
      run:
        working-directory: app
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and Angular CLI
        run: |
          npm ci
          npm install @angular/cli@14
      - name: "Run linter"
        run: npm run lint
      - name: "Run Angular tests"
        run: npm run test:prod
