name: API tests
run-name: Running API tests
on: [push]
jobs:
  Test-API:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          go-version: '1.18.0'
      - name: "Run Go tests"
        run: cd ./backend && ../run_tests.bash
